-- Jalankan seluruh SQL ini di Supabase SQL Editor.
-- Jangan menaruh service role key di database atau frontend.

create table if not exists public.conversations (
  id bigint generated by default as identity primary key,
  public_id varchar(20) not null unique,
  display_name varchar(40) not null default 'Pelanggan',
  status varchar(10) not null default 'open' check (status in ('open','closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint not null references public.conversations(id) on delete cascade,
  sender_type varchar(10) not null check (sender_type in ('customer','admin')),
  message text not null check (char_length(message) between 1 and 2000),
  is_read boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists messages_conversation_idx on public.messages(conversation_id, id);
create index if not exists conversations_updated_idx on public.conversations(updated_at desc);

-- Karena akses database dilakukan lewat server route dengan service-role key,
-- RLS dapat diaktifkan sebagai lapisan tambahan.
alter table public.conversations enable row level security;
alter table public.messages enable row level security;

-- Tidak membuat policy publik. Browser tidak diberi akses langsung ke tabel.
-- SERVICE ROLE di server route melewati RLS.
